#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
cd "$ROOT"

SX_BIN="${SX_BIN:-./zig-out/bin/sx}"
SX_SOURCE_BIN="$SX_BIN"
MINIZ_SRC="${MINIZ_SRC:-../miniz}"
CC="${CC:-clang}"
BENCH_CPU="${BENCH_CPU:-generic}"
BENCH_TRIALS="${BENCH_TRIALS:-5}"
BENCH_BASELINE_REF="${BENCH_BASELINE_REF:-}"
BENCH_BASELINE_REPO="${BENCH_BASELINE_REPO:-}"
BENCH_BASELINE_STDLIB_REF="${BENCH_BASELINE_STDLIB_REF:-HEAD}"
BENCH_ENFORCE_BASELINE="${BENCH_ENFORCE_BASELINE:-1}"
BENCHMARK_MARKDOWN="${BENCHMARK_MARKDOWN:-docs/benchmarks/compression.md}"

BASELINE_NOISE_PERCENT=1
BASELINE_NOISE_NS=10000
MINIZ_COMMIT=77d0dce8627735138c51770d1799a1ef48f2117d

SCRATCH_ROOT=.sx-tmp/bench-compress
mkdir -p "$SCRATCH_ROOT" "$(dirname "$BENCHMARK_MARKDOWN")"
LOCK_DIR="$SCRATCH_ROOT/lock"
RUN_DIR=$(mktemp -d "$SCRATCH_ROOT/run.XXXXXX")
SX_ENCODE="$RUN_DIR/sx-encode"
SX_DECODE="$RUN_DIR/sx-decode"
SX_EXACT="$RUN_DIR/sx-exact"
C_BENCH="$RUN_DIR/miniz-c"
BASELINE_ENCODE="$RUN_DIR/baseline-encode"
BASELINE_DECODE="$RUN_DIR/baseline-decode"
SX_LOG="$RUN_DIR/sx.log"
C_LOG="$RUN_DIR/c.log"
BASELINE_LOG="$RUN_DIR/baseline.log"
IDENTITY_LOG="$RUN_DIR/identity.log"
SX_EXACT_LOG="$RUN_DIR/sx-exact.log"
C_EXACT_LOG="$RUN_DIR/c-exact.log"
FROZEN_SX_BIN="$RUN_DIR/sx-compiler"
SX_COMPILER_STATUS_LOG="$RUN_DIR/sx-compiler-source-status.log"

started_utc=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
stage=initialization
report_written=0
lock_acquired=0

write_failure_markdown() {
    local exit_status=$1
    local report_tmp="${BENCHMARK_MARKDOWN}.tmp.$$"
    {
        echo "# Latest std.compress benchmark"
        echo
        echo "> Generated by \`tests/bench_compress.sh\` on $started_utc. Do not edit measured values by hand."
        echo
        echo "- Overall result: **FAIL**"
        echo "- Failed stage: \`$stage\`"
        echo "- Exit status: \`$exit_status\`"
        echo "- Measurements: unavailable; this failed run replaced the previous report so stale results cannot be mistaken for current evidence."
    } > "$report_tmp"
    mv "$report_tmp" "$BENCHMARK_MARKDOWN"
}

cleanup() {
    local exit_status=$?
    trap - EXIT
    set +e
    if [[ "$report_written" -ne 1 ]]; then
        write_failure_markdown "$exit_status"
    fi
    for implementation in sx c; do
        for corpus in repeat random; do
            for level in 1 6 9; do
                rm -f "$SCRATCH_ROOT/$implementation-$corpus-$level.zlib"
            done
        done
    done
    rm -f "$SCRATCH_ROOT/sx-exact.matrix" "$SCRATCH_ROOT/c-exact.matrix"
    rm -rf "$RUN_DIR"
    if [[ "$lock_acquired" -eq 1 ]]; then rmdir "$LOCK_DIR"; fi
    exit "$exit_status"
}
trap cleanup EXIT

stage="acquiring exclusive benchmark lock"
if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    # Another run owns the fixed SX/C byte-identity artifact paths and the
    # generated report. Do not overwrite its in-progress evidence.
    report_written=1
    echo "another std.compress benchmark is already running ($LOCK_DIR exists)" >&2
    exit 2
fi
lock_acquired=1

if ! [[ "$BENCH_TRIALS" =~ ^[1-9][0-9]*$ ]] || (( BENCH_TRIALS % 2 == 0 )); then
    echo "BENCH_TRIALS must be a positive odd integer" >&2
    exit 2
fi
if [[ "$BENCH_ENFORCE_BASELINE" != 0 && "$BENCH_ENFORCE_BASELINE" != 1 ]]; then
    echo "BENCH_ENFORCE_BASELINE must be 0 or 1" >&2
    exit 2
fi
if [[ -n "$BENCH_BASELINE_REPO" && -z "$BENCH_BASELINE_REF" ]]; then
    echo "BENCH_BASELINE_REPO requires BENCH_BASELINE_REF" >&2
    exit 2
fi
if ! command -v "$SX_BIN" >/dev/null 2>&1; then
    echo "sx compiler not found: $SX_BIN" >&2
    exit 2
fi
if ! command -v "$CC" >/dev/null 2>&1; then
    echo "C compiler not found: $CC" >&2
    exit 2
fi

sha256_file() {
    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{ print $1 }'
    elif command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{ print $1 }'
    elif command -v openssl >/dev/null 2>&1; then
        openssl dgst -sha256 "$1" | awk '{ print $NF }'
    else
        echo "no SHA-256 tool found (tried shasum, sha256sum, openssl)" >&2
        return 1
    fi
}

stage="freezing SX compiler binary"
sx_source_hash_before=$(sha256_file "$SX_SOURCE_BIN")
cp "$SX_SOURCE_BIN" "$FROZEN_SX_BIN"
chmod +x "$FROZEN_SX_BIN"
sx_frozen_hash_before=$(sha256_file "$FROZEN_SX_BIN")
sx_source_hash_after_copy=$(sha256_file "$SX_SOURCE_BIN")
if [[ "$sx_source_hash_before" != "$sx_source_hash_after_copy" ||
      "$sx_source_hash_before" != "$sx_frozen_hash_before" ]]; then
    echo "SX compiler changed while its benchmark snapshot was being created" >&2
    echo "source before:     $sx_source_hash_before" >&2
    echo "source after copy: $sx_source_hash_after_copy" >&2
    echo "frozen copy:       $sx_frozen_hash_before" >&2
    exit 2
fi
sx_git_head=$(git rev-parse HEAD 2>/dev/null || printf unavailable)
if git status --short -- src build.zig build.zig.zon > "$SX_COMPILER_STATUS_LOG" 2>/dev/null; then
    sx_compiler_dirty_count=$(awk 'NF { count += 1 } END { print count + 0 }' "$SX_COMPILER_STATUS_LOG")
    if [[ "$sx_compiler_dirty_count" -eq 0 ]]; then
        sx_compiler_source_state="clean"
    else
        sx_compiler_source_state="dirty ($sx_compiler_dirty_count paths with uncommitted changes)"
    fi
else
    : > "$SX_COMPILER_STATUS_LOG"
    sx_compiler_dirty_count=0
    sx_compiler_source_state="unavailable"
fi

verify_miniz_file() {
    local name=$1
    local expected=$2
    local path="$MINIZ_SRC/$name"
    local actual
    if [[ ! -f "$path" ]]; then
        echo "pinned miniz source is missing $path" >&2
        return 1
    fi
    actual=$(sha256_file "$path")
    if [[ "$actual" != "$expected" ]]; then
        echo "pinned miniz hash mismatch for $name" >&2
        echo "expected: $expected" >&2
        echo "actual:   $actual" >&2
        return 1
    fi
}

stage="verifying pinned miniz $MINIZ_COMMIT"
verify_miniz_file miniz.c f23204efee2bfaffb72a974d2e28c64c3c1d9787144b5c5890f129c465e467bd
verify_miniz_file miniz.h f0b67217bdd8e45b74eb9b7c2c7ae20ed6760a1d76f3276b93617039ebd082df
verify_miniz_file miniz_common.h f1ba29821c8caef83585b328196aa346c5da7c82890a70a3d10d77c6cec0ed39
verify_miniz_file miniz_tdef.c 85b93205232d51d092f24041934d951f11f9edc02df1f475e8ceb7b281a1e7f6
verify_miniz_file miniz_tdef.h d62da02953c3834dfcbde4db026c6d9345013ef9b0e53185131016a3a4e48c33
verify_miniz_file miniz_tinfl.c 2296ebd21ef9af5ebbefd5b454d4bb67d8fb4af2d24945e7fb32114374f75a76
verify_miniz_file miniz_tinfl.h da4850920fdf09f8877d9affabe1ebba1852ce4b1ebbd121f2ba7a7ea8e57e5d

miniz_revision=unavailable
if git -C "$MINIZ_SRC" rev-parse HEAD >/dev/null 2>&1; then
    miniz_revision=$(git -C "$MINIZ_SRC" rev-parse HEAD)
fi

metric() {
    local log=$1 corpus=$2 level=$3 key=$4
    awk -v corpus="$corpus" -v level="$level" -v key="$key" '
        $1 == corpus {
            matched_level = 0
            for (i = 2; i <= NF; ++i) {
                split($i, pair, "=")
                if (pair[1] == "level" && pair[2] == level) matched_level = 1
            }
            if (matched_level) {
                for (i = 2; i <= NF; ++i) {
                    split($i, pair, "=")
                    if (pair[1] == key) { print pair[2]; exit }
                }
            }
        }
    ' "$log"
}

read_metric() {
    local value
    value=$(metric "$1" "$2" "$3" "$4")
    if ! [[ "$value" =~ ^[0-9]+$ ]]; then
        echo "missing or invalid metric: log=$1 corpus=$2 level=$3 key=$4" >&2
        return 1
    fi
    printf '%s' "$value"
}

median() {
    printf '%s\n' "$@" | sort -n | awk '{ values[NR] = $1 } END { print values[(NR + 1) / 2] }'
}

aggregate_logs() {
    local output=$1
    shift
    : > "$output"
    local first=$1 corpus level input packed ratio encode_ns decode_ns log
    local -a encode_values decode_values
    for corpus in repetitive incompressible; do
        for level in 1 6 9; do
            input=$(read_metric "$first" "$corpus" "$level" input)
            packed=$(read_metric "$first" "$corpus" "$level" packed)
            ratio=$(read_metric "$first" "$corpus" "$level" ratio_permille)
            encode_values=()
            decode_values=()
            for log in "$@"; do
                encode_values+=("$(read_metric "$log" "$corpus" "$level" encode_ns)")
                decode_values+=("$(read_metric "$log" "$corpus" "$level" decode_ns)")
            done
            encode_ns=$(median "${encode_values[@]}")
            decode_ns=$(median "${decode_values[@]}")
            printf '%s level=%s input=%s packed=%s ratio_permille=%s encode_ns=%s decode_ns=%s encode_KiB_s=%s decode_KiB_s=%s\n' \
                "$corpus" "$level" "$input" "$packed" "$ratio" "$encode_ns" "$decode_ns" \
                "$((input * 1000000000 / 1024 / (encode_ns > 0 ? encode_ns : 1)))" \
                "$((input * 1000000000 / 1024 / (decode_ns > 0 ? decode_ns : 1)))" >> "$output"
        done
    done
}

run_sx_bench() {
    local encode_bench=$1 decode_bench=$2 output=$3
    "$encode_bench" > "$output"
    "$decode_bench" >> "$output"
}

speedup() {
    awk -v c_ns="$1" -v sx_ns="$2" 'BEGIN {
        if (sx_ns <= 0 || c_ns <= 0) { print "n/a"; exit }
        printf "%.3fx", c_ns / sx_ns
    }'
}

baseline_change() {
    awk -v baseline_ns="$1" -v current_ns="$2" 'BEGIN {
        if (baseline_ns <= 0 || current_ns <= 0) { print "n/a"; exit }
        printf "%+.2f%%", 100 * (current_ns - baseline_ns) / baseline_ns
    }'
}

paired_baseline_change_ppm() {
    local corpus=$1 level=$2 key=$3 pair current_ns baseline_ns
    local -a changes=()
    for ((pair = 0; pair < ${#sx_trials[@]}; ++pair)); do
        current_ns=$(read_metric "${sx_trials[$pair]}" "$corpus" "$level" "$key")
        baseline_ns=$(read_metric "${baseline_trials[$pair]}" "$corpus" "$level" "$key")
        changes+=("$(((current_ns - baseline_ns) * 1000000 / baseline_ns))")
    done
    median "${changes[@]}"
}

paired_baseline_change() {
    awk -v change_ppm="$1" 'BEGIN { printf "%+.2f%%", change_ppm / 10000 }'
}

paired_baseline_delta_ns() {
    local corpus=$1 level=$2 key=$3 pair current_ns baseline_ns
    local -a deltas=()
    for ((pair = 0; pair < ${#sx_trials[@]}; ++pair)); do
        current_ns=$(read_metric "${sx_trials[$pair]}" "$corpus" "$level" "$key")
        baseline_ns=$(read_metric "${baseline_trials[$pair]}" "$corpus" "$level" "$key")
        deltas+=("$((current_ns - baseline_ns))")
    done
    median "${deltas[@]}"
}

paired_baseline_status() {
    local change_ppm=$1 delta_ns=$2
    if (( change_ppm <= 0 || delta_ns <= 0 )); then
        printf 'PASS'
    elif (( change_ppm <= BASELINE_NOISE_PERCENT * 10000 || delta_ns <= BASELINE_NOISE_NS )); then
        printf 'NOISE'
    else
        printf 'REGRESSION'
    fi
}

count_baseline_regressions() {
    local regressions=0 corpus level key change_ppm delta_ns
    for corpus in repetitive incompressible; do
        for level in 1 6 9; do
            for key in encode_ns decode_ns; do
                change_ppm=$(paired_baseline_change_ppm "$corpus" "$level" "$key")
                delta_ns=$(paired_baseline_delta_ns "$corpus" "$level" "$key")
                if (( change_ppm > BASELINE_NOISE_PERCENT * 10000 && delta_ns > BASELINE_NOISE_NS )); then
                    regressions=$((regressions + 1))
                fi
            done
        done
    done
    printf '%s' "$regressions"
}

paired_total_delta_ns() {
    local pair corpus level key current_ns baseline_ns total_delta
    local -a deltas=()
    for ((pair = 0; pair < ${#sx_trials[@]}; ++pair)); do
        total_delta=0
        for corpus in repetitive incompressible; do
            for level in 1 6 9; do
                for key in encode_ns decode_ns; do
                    current_ns=$(read_metric "${sx_trials[$pair]}" "$corpus" "$level" "$key")
                    baseline_ns=$(read_metric "${baseline_trials[$pair]}" "$corpus" "$level" "$key")
                    total_delta=$((total_delta + current_ns - baseline_ns))
                done
            done
        done
        deltas+=("$total_delta")
    done
    median "${deltas[@]}"
}

paired_total_change_ppm() {
    local pair corpus level key current_ns baseline_ns total_current total_baseline
    local -a changes=()
    for ((pair = 0; pair < ${#sx_trials[@]}; ++pair)); do
        total_current=0
        total_baseline=0
        for corpus in repetitive incompressible; do
            for level in 1 6 9; do
                for key in encode_ns decode_ns; do
                    current_ns=$(read_metric "${sx_trials[$pair]}" "$corpus" "$level" "$key")
                    baseline_ns=$(read_metric "${baseline_trials[$pair]}" "$corpus" "$level" "$key")
                    total_current=$((total_current + current_ns))
                    total_baseline=$((total_baseline + baseline_ns))
                done
            done
        done
        changes+=("$(((total_current - total_baseline) * 1000000 / total_baseline))")
    done
    median "${changes[@]}"
}

paired_gross_delta_ns() {
    local direction=$1 corpus level key delta total=0
    for corpus in repetitive incompressible; do
        for level in 1 6 9; do
            for key in encode_ns decode_ns; do
                delta=$(paired_baseline_delta_ns "$corpus" "$level" "$key")
                if [[ "$direction" == gain && "$delta" -lt 0 ]]; then
                    total=$((total - delta))
                elif [[ "$direction" == loss && "$delta" -gt 0 ]]; then
                    total=$((total + delta))
                fi
            done
        done
    done
    printf '%s' "$total"
}

baseline_gate_status() {
    local regressions=$1 total_change_ppm=$2 total_delta_ns=$3
    if (( regressions == 0 )); then
        printf 'PASS'
    elif (( total_change_ppm < -BASELINE_NOISE_PERCENT * 10000 && total_delta_ns < -BASELINE_NOISE_NS )); then
        printf 'PASS'
    else
        printf 'FAIL'
    fi
}

policy_assert() {
    local label=$1 actual=$2 expected=$3
    if [[ "$actual" != "$expected" ]]; then
        echo "regression-policy self-test failed: $label: expected $expected, got $actual" >&2
        return 1
    fi
}

stage="self-testing regression policy boundaries"
policy_assert "faster row" "$(paired_baseline_status -1 -1)" PASS
policy_assert "absolute boundary is noise" "$(paired_baseline_status 20000 10000)" NOISE
policy_assert "percentage boundary is noise" "$(paired_baseline_status 10000 20000)" NOISE
policy_assert "both boundaries exceeded" "$(paired_baseline_status 10001 10001)" REGRESSION
policy_assert "no significant rows" "$(baseline_gate_status 0 1 1)" PASS
policy_assert "large aggregate gain offsets a regression" "$(baseline_gate_status 1 -10001 -10001)" PASS
policy_assert "percentage gain boundary does not offset" "$(baseline_gate_status 1 -10000 -10001)" FAIL
policy_assert "absolute gain boundary does not offset" "$(baseline_gate_status 1 -10001 -10000)" FAIL

write_markdown() {
    local report_tmp="${BENCHMARK_MARKDOWN}.tmp.$$"
    local overall_status=PASS corpus level sx_input sx_packed sx_encode sx_decode c_encode c_decode identity
    local baseline_ns current_ns change_ppm delta_ns metric_name
    if [[ "$identity_ok" -ne 1 || "$tradeoff_status" == FAIL ]]; then
        overall_status=FAIL
    elif [[ "$baseline_available" -ne 1 ]]; then
        overall_status=INFORMATIONAL
    fi
    {
        echo "# Latest std.compress benchmark"
        echo
        echo "> Generated by \`tests/bench_compress.sh\` on $(date -u '+%Y-%m-%d %H:%M:%S UTC'). Do not edit measured values by hand."
        echo
        echo "- Overall result: **$overall_status**"
        echo "- Workload: public \`std.zlib.encode\` and \`std.zlib.decode\`"
        echo "- CPU target: \`$BENCH_CPU\` for both compilers"
        echo "- SX: \`--opt 3\`"
        echo "- Frozen SX compiler source: \`$SX_SOURCE_BIN\`"
        echo "- Frozen SX compiler SHA-256 before/after: \`$sx_frozen_hash_before\` / \`$sx_frozen_hash_after\`"
        echo "- Source SX compiler SHA-256 before/after: \`$sx_source_hash_before\` / \`$sx_source_hash_after\`"
        echo "- SX compiler source state: Git HEAD \`$sx_git_head\`, **$sx_compiler_source_state**; the executable hash above is the authoritative compiler identity"
        echo "- C oracle: pinned miniz 3.1.2 \`$MINIZ_COMMIT\`, compiled with \`$CC -O3\`"
        echo "- Detected miniz checkout revision: \`$miniz_revision\` (all seven codec source/header hashes matched the pin)"
        echo "- Exact-byte gate: **$(if [[ "$identity_ok" -eq 1 ]]; then printf PASS; else printf FAIL; fi)** (110-case level/strategy matrix plus all six timed artifacts)"
        echo "- Timing unit: nanoseconds per operation; each process trial is the median of 15 timed operations after 3 warmups, and each reported value is the median of $BENCH_TRIALS process trials"
        echo "- SX encoding and decoding use separate executables so one loop cannot perturb the other loop's code layout"
        if [[ "$baseline_available" -eq 1 ]]; then
            echo "- Accepted SX baseline: \`$baseline_label\`; $baseline_description"
        else
            echo "- Accepted SX baseline: **not configured**; timings are informational and cannot establish that SX performance did not regress"
        fi
        if [[ "$sx_compiler_dirty_count" -gt 0 ]]; then
            echo
            echo "<details><summary>Uncommitted compiler/build source paths</summary>"
            echo
            echo '```text'
            cat "$SX_COMPILER_STATUS_LOG"
            echo '```'
            echo "</details>"
        fi
        echo
        echo "## Exact-output matrix"
        echo
        echo "The untimed compatibility gate covers both 1 MiB corpora, levels 0 through 10, and every public strategy: \`default\`, \`filtered\`, \`huffman_only\`, \`rle\`, and \`fixed\`. Each implementation writes the same 16-byte length-prefixed record format, followed by the complete compressed bytes."
        echo
        echo "- Expected cases: 110 (2 corpora × 11 levels × 5 strategies)"
        echo "- SX cases produced: $sx_exact_cases"
        echo "- miniz C cases produced: $c_exact_cases"
        echo "- Case manifest comparison: **$(if [[ "$exact_manifest_ok" -eq 1 ]]; then printf PASS; else printf FAIL; fi)**"
        echo "- Full byte-matrix comparison: **$(if [[ "$exact_matrix_ok" -eq 1 ]]; then printf PASS; else printf FAIL; fi)**"
        echo
        echo "<details><summary>Exact matrix manifest</summary>"
        echo
        echo '```text'
        cat "$SX_EXACT_LOG"
        echo '```'
        echo "</details>"
        echo
        echo "## Latency and exact output"
        echo
        echo "Speedup is \`C time / SX time\`; values above 1.000x mean SX is faster."
        echo
        echo "| Corpus | Level | Input bytes | Packed bytes | Identical | SX encode ns | C encode ns | Encode speedup | SX decode ns | C decode ns | Decode speedup |"
        echo "|---|---:|---:|---:|:---:|---:|---:|---:|---:|---:|---:|"
        for corpus in repetitive incompressible; do
            for level in 1 6 9; do
                sx_input=$(read_metric "$SX_LOG" "$corpus" "$level" input)
                sx_packed=$(read_metric "$SX_LOG" "$corpus" "$level" packed)
                sx_encode=$(read_metric "$SX_LOG" "$corpus" "$level" encode_ns)
                sx_decode=$(read_metric "$SX_LOG" "$corpus" "$level" decode_ns)
                c_encode=$(read_metric "$C_LOG" "$corpus" "$level" encode_ns)
                c_decode=$(read_metric "$C_LOG" "$corpus" "$level" decode_ns)
                if [[ "$corpus" == repetitive ]]; then identity_corpus=repeat; else identity_corpus=random; fi
                identity=$(awk -v corpus="$identity_corpus" -v level="$level" '$1 == corpus && $2 == "level=" level { split($3, pair, "="); print pair[2]; exit }' "$IDENTITY_LOG")
                printf '| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n' \
                    "$corpus" "$level" "$sx_input" "$sx_packed" "$identity" \
                    "$sx_encode" "$c_encode" "$(speedup "$c_encode" "$sx_encode")" \
                    "$sx_decode" "$c_decode" "$(speedup "$c_decode" "$sx_decode")"
            done
        done
        echo
        echo "## Accepted baseline comparison"
        echo
        if [[ "$baseline_available" -eq 1 ]]; then
            echo "A row is a regression only when its median paired slowdown exceeds both ${BASELINE_NOISE_PERCENT}% and ${BASELINE_NOISE_NS} ns. Individual regressions remain visible, but a small loss cannot veto a meaningful aggregate gain: the tradeoff gate also passes when the paired total improves by more than both thresholds."
            echo
            echo "- Tradeoff gate: **$tradeoff_status**"
            echo "- Enforcement: **$(if [[ "$BENCH_ENFORCE_BASELINE" -eq 1 ]]; then printf enabled; else printf report-only; fi)**"
            echo "- Paired total delta: ${total_delta_ns} ns ($(paired_baseline_change "$total_change_ppm"))"
            echo "- Gross row gains: ${gross_gain_ns} ns"
            echo "- Gross row losses: ${gross_loss_ns} ns"
            echo "- Individually significant regressions: ${baseline_regressions}"
            echo
            echo "| Corpus | Level | Metric | Baseline SX ns | Current SX ns | Aggregate change | Paired median delta ns | Paired median change | Status |"
            echo "|---|---:|---|---:|---:|---:|---:|---:|:---:|"
            for corpus in repetitive incompressible; do
                for level in 1 6 9; do
                    for metric_name in encode decode; do
                        baseline_ns=$(read_metric "$BASELINE_LOG" "$corpus" "$level" "${metric_name}_ns")
                        current_ns=$(read_metric "$SX_LOG" "$corpus" "$level" "${metric_name}_ns")
                        change_ppm=$(paired_baseline_change_ppm "$corpus" "$level" "${metric_name}_ns")
                        delta_ns=$(paired_baseline_delta_ns "$corpus" "$level" "${metric_name}_ns")
                        printf '| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n' \
                            "$corpus" "$level" "$metric_name" "$baseline_ns" "$current_ns" \
                            "$(baseline_change "$baseline_ns" "$current_ns")" "$delta_ns" \
                            "$(paired_baseline_change "$change_ppm")" \
                            "$(paired_baseline_status "$change_ppm" "$delta_ns")"
                    done
                done
            done
        else
            echo "**NOT EVALUATED.** Set \`BENCH_BASELINE_REF=<accepted-commit>\` to rebuild that revision's stdlib and run the paired gain-versus-regression gate. A run without a baseline is never reported as a performance pass."
        fi
        echo
        echo "## Throughput"
        echo
        echo "| Corpus | Level | SX encode KiB/s | C encode KiB/s | SX decode KiB/s | C decode KiB/s |"
        echo "|---|---:|---:|---:|---:|---:|"
        for corpus in repetitive incompressible; do
            for level in 1 6 9; do
                printf '| %s | %s | %s | %s | %s | %s |\n' \
                    "$corpus" "$level" \
                    "$(read_metric "$SX_LOG" "$corpus" "$level" encode_KiB_s)" \
                    "$(read_metric "$C_LOG" "$corpus" "$level" encode_KiB_s)" \
                    "$(read_metric "$SX_LOG" "$corpus" "$level" decode_KiB_s)" \
                    "$(read_metric "$C_LOG" "$corpus" "$level" decode_KiB_s)"
            done
        done
        echo
        echo "## Raw output"
        echo
        echo "<details><summary>SX stdlib</summary>"
        echo
        echo '```text'
        cat "$SX_LOG"
        echo '```'
        echo "</details>"
        echo
        echo "<details><summary>miniz C -O3</summary>"
        echo
        echo '```text'
        cat "$C_LOG"
        echo '```'
        echo "</details>"
        if [[ "$baseline_available" -eq 1 ]]; then
            echo
            echo "<details><summary>accepted SX baseline ($baseline_label)</summary>"
            echo
            echo '```text'
            cat "$BASELINE_LOG"
            echo '```'
            echo "</details>"
        fi
        echo
        echo "## Reproduce"
        echo
        echo '```sh'
        echo 'tests/bench_compress.sh'
        echo 'BENCH_BASELINE_REF=<accepted-commit> tests/bench_compress.sh'
        echo 'BENCH_BASELINE_REPO=<historical-repo> BENCH_BASELINE_REF=<accepted-commit> BENCH_BASELINE_STDLIB_REF=<sx-support-commit> tests/bench_compress.sh'
        echo '```'
    } > "$report_tmp"
    mv "$report_tmp" "$BENCHMARK_MARKDOWN"
    report_written=1
    echo "markdown report: $BENCHMARK_MARKDOWN"
}

stage="building current SX public-codec benchmarks"
env SX_STDLIB_PATH="$ROOT/library" "$FROZEN_SX_BIN" build --opt 3 --cpu "$BENCH_CPU" -o "$SX_ENCODE" tests/bench_compress_encode.sx
env SX_STDLIB_PATH="$ROOT/library" "$FROZEN_SX_BIN" build --opt 3 --cpu "$BENCH_CPU" -o "$SX_DECODE" tests/bench_compress_decode.sx
env SX_STDLIB_PATH="$ROOT/library" "$FROZEN_SX_BIN" build --opt 3 --cpu "$BENCH_CPU" -o "$SX_EXACT" tests/bench_compress_exact.sx

baseline_available=0
baseline_label=""
baseline_description=""
if [[ -n "$BENCH_BASELINE_REF" ]]; then
    baseline_tree="$RUN_DIR/baseline"
    mkdir -p "$baseline_tree/tests"
    if [[ -n "$BENCH_BASELINE_REPO" ]]; then
        stage="building historical SX baseline $BENCH_BASELINE_REPO@$BENCH_BASELINE_REF"
        git -C "$BENCH_BASELINE_REPO" archive "$BENCH_BASELINE_REF" | tar -x -C "$baseline_tree"
        if [[ ! -f "$baseline_tree/miniz.sx" ||
              ! -f "$baseline_tree/tests/bench.sx" ||
              ! -f "$baseline_tree/tests/bench_decode.sx" ]]; then
            echo "historical baseline must contain miniz.sx and tests/{bench.sx,bench_decode.sx}" >&2
            exit 2
        fi
        sed 's#/tmp/sx-miniz-bench-sx-#.sx-tmp/bench-compress/sx-#g' \
            "$baseline_tree/tests/bench.sx" > "$baseline_tree/tests/bench_local.sx"
        sed 's#/tmp/sx-miniz-bench-sx-#.sx-tmp/bench-compress/sx-#g' \
            "$baseline_tree/tests/bench_decode.sx" > "$baseline_tree/tests/bench_decode_local.sx"
        baseline_stdlib_tree="$RUN_DIR/baseline-stdlib"
        mkdir -p "$baseline_stdlib_tree"
        git archive "$BENCH_BASELINE_STDLIB_REF" library | tar -x -C "$baseline_stdlib_tree"
        env SX_STDLIB_PATH="$baseline_stdlib_tree/library" "$FROZEN_SX_BIN" build --opt 3 --cpu "$BENCH_CPU" -o "$BASELINE_ENCODE" "$baseline_tree/tests/bench_local.sx"
        env SX_STDLIB_PATH="$baseline_stdlib_tree/library" "$FROZEN_SX_BIN" build --opt 3 --cpu "$BENCH_CPU" -o "$BASELINE_DECODE" "$baseline_tree/tests/bench_decode_local.sx"
        baseline_label="$BENCH_BASELINE_REPO@$BENCH_BASELINE_REF"
        baseline_description="the historical implementation was rebuilt with the current compiler and stdlib support from \`$BENCH_BASELINE_STDLIB_REF\`, then measured in paired, rotated trials"
    else
        stage="building accepted SX baseline $BENCH_BASELINE_REF"
        git archive "$BENCH_BASELINE_REF" | tar -x -C "$baseline_tree"
        cp tests/bench_compress_encode.sx tests/bench_compress_decode.sx "$baseline_tree/tests/"
        env SX_STDLIB_PATH="$baseline_tree/library" "$FROZEN_SX_BIN" build --opt 3 --cpu "$BENCH_CPU" -o "$BASELINE_ENCODE" "$baseline_tree/tests/bench_compress_encode.sx"
        env SX_STDLIB_PATH="$baseline_tree/library" "$FROZEN_SX_BIN" build --opt 3 --cpu "$BENCH_CPU" -o "$BASELINE_DECODE" "$baseline_tree/tests/bench_compress_decode.sx"
        baseline_label="$BENCH_BASELINE_REF"
        baseline_description="that revision's stdlib sources were rebuilt with the current compiler and measured in paired, rotated trials"
    fi
    baseline_available=1
fi

stage="building pinned miniz C -O3 benchmark"
common_c_args=(-std=c99 -O3 -DNDEBUG
    -DMINIZ_USE_UNALIGNED_LOADS_AND_STORES=1
    -DMINIZ_LITTLE_ENDIAN=1
    -DMINIZ_HAS_64BIT_REGISTERS=1
    -Itests
    -I"$MINIZ_SRC")
case "$(uname -m)" in
    arm64|aarch64)
        "$CC" "${common_c_args[@]}" "-mcpu=$BENCH_CPU" \
            tests/bench_compress_miniz.c "$MINIZ_SRC/miniz.c" \
            "$MINIZ_SRC/miniz_tinfl.c" "$MINIZ_SRC/miniz_tdef.c" \
            -o "$C_BENCH"
        ;;
    x86_64|amd64)
        c_arch="$BENCH_CPU"
        if [[ "$c_arch" == generic ]]; then c_arch=x86-64; fi
        "$CC" "${common_c_args[@]}" "-march=$c_arch" \
            tests/bench_compress_miniz.c "$MINIZ_SRC/miniz.c" \
            "$MINIZ_SRC/miniz_tinfl.c" "$MINIZ_SRC/miniz_tdef.c" \
            -o "$C_BENCH"
        ;;
    *)
        "$CC" "${common_c_args[@]}" \
            tests/bench_compress_miniz.c "$MINIZ_SRC/miniz.c" \
            "$MINIZ_SRC/miniz_tinfl.c" "$MINIZ_SRC/miniz_tdef.c" \
            -o "$C_BENCH"
        ;;
esac

stage="running rotated process trials"
echo "process trials (rotating execution order)"
sx_trials=()
c_trials=()
baseline_trials=()
for ((trial = 1; trial <= BENCH_TRIALS; ++trial)); do
    sx_trial_log="$RUN_DIR/sx-$trial.log"
    c_trial_log="$RUN_DIR/c-$trial.log"
    baseline_trial_log="$RUN_DIR/baseline-$trial.log"
    if [[ "$baseline_available" -eq 1 ]]; then
        case $((trial % 3)) in
            1)
                run_sx_bench "$BASELINE_ENCODE" "$BASELINE_DECODE" "$baseline_trial_log"
                run_sx_bench "$SX_ENCODE" "$SX_DECODE" "$sx_trial_log"
                "$C_BENCH" > "$c_trial_log"
                ;;
            2)
                run_sx_bench "$SX_ENCODE" "$SX_DECODE" "$sx_trial_log"
                "$C_BENCH" > "$c_trial_log"
                run_sx_bench "$BASELINE_ENCODE" "$BASELINE_DECODE" "$baseline_trial_log"
                ;;
            0)
                "$C_BENCH" > "$c_trial_log"
                run_sx_bench "$BASELINE_ENCODE" "$BASELINE_DECODE" "$baseline_trial_log"
                run_sx_bench "$SX_ENCODE" "$SX_DECODE" "$sx_trial_log"
                ;;
        esac
    elif (( trial % 2 == 0 )); then
        "$C_BENCH" > "$c_trial_log"
        run_sx_bench "$SX_ENCODE" "$SX_DECODE" "$sx_trial_log"
    else
        run_sx_bench "$SX_ENCODE" "$SX_DECODE" "$sx_trial_log"
        "$C_BENCH" > "$c_trial_log"
    fi
    sx_trials+=("$sx_trial_log")
    c_trials+=("$c_trial_log")
    if [[ "$baseline_available" -eq 1 ]]; then baseline_trials+=("$baseline_trial_log"); fi
    echo "  process trial $trial/$BENCH_TRIALS"
done

stage="aggregating benchmark samples"
echo "sx (--opt 3 --cpu $BENCH_CPU)"
aggregate_logs "$SX_LOG" "${sx_trials[@]}"
cat "$SX_LOG"

echo "miniz C (-O3 cpu=$BENCH_CPU)"
aggregate_logs "$C_LOG" "${c_trials[@]}"
cat "$C_LOG"

if [[ "$baseline_available" -eq 1 ]]; then
    echo "accepted SX baseline ($baseline_label, --opt 3 --cpu $BENCH_CPU)"
    aggregate_logs "$BASELINE_LOG" "${baseline_trials[@]}"
    cat "$BASELINE_LOG"
fi

stage="verifying full compressed-byte identity"
"$SX_ENCODE" >/dev/null
identity_ok=1
: > "$IDENTITY_LOG"
echo "byte identity"
for corpus in repeat random; do
    for level in 1 6 9; do
        if cmp -s "$SCRATCH_ROOT/sx-$corpus-$level.zlib" "$SCRATCH_ROOT/c-$corpus-$level.zlib"; then
            identity_line="$corpus level=$level identical=yes"
        else
            first_difference=$(cmp -l "$SCRATCH_ROOT/sx-$corpus-$level.zlib" "$SCRATCH_ROOT/c-$corpus-$level.zlib" 2>/dev/null | head -n 1 || true)
            identity_line="$corpus level=$level identical=no first_difference=$first_difference"
            identity_ok=0
        fi
        echo "$identity_line" | tee -a "$IDENTITY_LOG"
    done
done

stage="verifying levels 0-10 and every public strategy"
"$SX_EXACT" > "$SX_EXACT_LOG"
"$C_BENCH" --exact > "$C_EXACT_LOG"
sx_exact_cases=$(awk 'END { print NR + 0 }' "$SX_EXACT_LOG")
c_exact_cases=$(awk 'END { print NR + 0 }' "$C_EXACT_LOG")
exact_manifest_ok=0
exact_matrix_ok=0
if [[ "$sx_exact_cases" -eq 110 && "$c_exact_cases" -eq 110 ]] && cmp -s "$SX_EXACT_LOG" "$C_EXACT_LOG"; then
    exact_manifest_ok=1
fi
if cmp -s "$SCRATCH_ROOT/sx-exact.matrix" "$SCRATCH_ROOT/c-exact.matrix"; then
    exact_matrix_ok=1
fi
if [[ "$exact_manifest_ok" -ne 1 || "$exact_matrix_ok" -ne 1 ]]; then
    identity_ok=0
fi
echo "exact matrix: cases=$sx_exact_cases/110 manifest=$(if [[ "$exact_manifest_ok" -eq 1 ]]; then printf PASS; else printf FAIL; fi) bytes=$(if [[ "$exact_matrix_ok" -eq 1 ]]; then printf PASS; else printf FAIL; fi)"

tradeoff_status="NOT EVALUATED"
baseline_regressions=0
total_delta_ns=0
total_change_ppm=0
gross_gain_ns=0
gross_loss_ns=0
if [[ "$baseline_available" -eq 1 ]]; then
    stage="evaluating paired baseline tradeoffs"
    baseline_regressions=$(count_baseline_regressions)
    total_delta_ns=$(paired_total_delta_ns)
    total_change_ppm=$(paired_total_change_ppm)
    gross_gain_ns=$(paired_gross_delta_ns gain)
    gross_loss_ns=$(paired_gross_delta_ns loss)
    tradeoff_status=$(baseline_gate_status "$baseline_regressions" "$total_change_ppm" "$total_delta_ns")
fi

stage="verifying frozen SX compiler provenance"
sx_frozen_hash_after=$(sha256_file "$FROZEN_SX_BIN")
sx_source_hash_after=$(sha256_file "$SX_SOURCE_BIN")
if [[ "$sx_frozen_hash_before" != "$sx_frozen_hash_after" ||
      "$sx_source_hash_before" != "$sx_source_hash_after" ]]; then
    echo "SX compiler provenance changed during the benchmark" >&2
    echo "frozen before: $sx_frozen_hash_before" >&2
    echo "frozen after:  $sx_frozen_hash_after" >&2
    echo "source before: $sx_source_hash_before" >&2
    echo "source after:  $sx_source_hash_after" >&2
    exit 2
fi

stage="writing benchmark Markdown"
write_markdown

if [[ "$identity_ok" -ne 1 ]]; then
    echo "compressed bytes differ from pinned miniz C" >&2
    exit 1
fi
if [[ "$baseline_available" -eq 1 ]]; then
    echo "accepted baseline regressions: $baseline_regressions"
    echo "accepted baseline paired total: ${total_delta_ns} ns ($(paired_baseline_change "$total_change_ppm")); tradeoff gate: $tradeoff_status"
    if [[ "$BENCH_ENFORCE_BASELINE" -eq 1 && "$tradeoff_status" != PASS ]]; then
        exit 1
    fi
elif [[ "$BENCH_ENFORCE_BASELINE" -eq 1 ]]; then
    echo "no accepted baseline configured; performance result is informational" >&2
fi
